#!/usr/bin/env python3
"""
plot_yaw_pd_controller_logs.py

Plots 5 key figures for YawPDController.py logs:
1) XY trajectory with goal marked
2) Z tracking: z vs z_des
3) Yaw tracking: yaw vs yaw_des
4) Yaw error vs time
5) XY distance-to-go: e_xy_norm vs time

Works for any CSV generated by YawPDController.py.

Run examples:
python3 plot_yaw_pd_controller_logs.py ~/Desktop/YawPDController_owl1.csv --show
python3 plot_yaw_pd_controller_logs.py ~/Desktop/YawPDController_owl2.csv --show
python3 plot_yaw_pd_controller_logs.py ~/Desktop/YawPDController_owl*.csv --show
python3 plot_yaw_pd_controller_logs.py ~/Desktop/YawPDController_owl*.csv --outdir ~/Desktop/yaw_pd_plots
python3 plot_yaw_pd_controller_logs.py ~/Desktop/YawPDController_owl1.csv --outdir ~/Desktop/yaw_pd_plots --prefix owl
"""

import argparse
import os
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


def to_num(series):
    return pd.to_numeric(series, errors="coerce")


def load_csv(path):
    df = pd.read_csv(path)

    for c in df.columns:
        if c == "phase":
            df[c] = df[c].astype(str)
        else:
            df[c] = to_num(df[c])

    df = df.dropna(subset=["t"]).copy()
    return df


def pick_first_finite(series, fallback=np.nan):
    s = series.dropna()
    return float(s.iloc[0]) if len(s) else fallback


def sanitize_name(name):
    return "".join(ch if ch.isalnum() or ch in ("-", "_") else "_" for ch in name)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("csv", nargs="+", help="One or more YawPDController CSV files")
    ap.add_argument("--show", action="store_true", help="Show plots interactively")
    ap.add_argument("--outdir", default="", help="Folder to save PNGs")
    ap.add_argument("--prefix", default="YawPDController", help="Filename prefix for saved PNGs")
    ap.add_argument("--decimate", type=int, default=1, help="Plot every Nth sample")
    args = ap.parse_args()

    save = bool(args.outdir)
    if save:
        os.makedirs(args.outdir, exist_ok=True)

    dec = max(1, args.decimate)
    sl = slice(None, None, dec)

    for csv_path in args.csv:
        df = load_csv(csv_path)
        stem = sanitize_name(Path(csv_path).stem)

        t = df["t"].to_numpy()

        x = df.get("x", pd.Series(np.nan, index=df.index)).to_numpy()
        y = df.get("y", pd.Series(np.nan, index=df.index)).to_numpy()
        z = df.get("z", pd.Series(np.nan, index=df.index)).to_numpy()

        x_des = pick_first_finite(df["x_des"]) if "x_des" in df else np.nan
        y_des = pick_first_finite(df["y_des"]) if "y_des" in df else np.nan
        z_des = pick_first_finite(df["z_des"]) if "z_des" in df else np.nan

        yaw = df.get("yaw_deg", pd.Series(np.nan, index=df.index)).to_numpy()
        yaw_des = df.get("yaw_des_deg", pd.Series(np.nan, index=df.index)).to_numpy()
        yaw_err = df.get("yaw_err_deg", pd.Series(np.nan, index=df.index)).to_numpy()
        e_xy_norm = df.get("e_xy_norm", pd.Series(np.nan, index=df.index)).to_numpy()

        def savefig(name):
            if save:
                out = os.path.join(args.outdir, f"{args.prefix}_{stem}_{name}.png")
                plt.savefig(out, dpi=200, bbox_inches="tight")

        # -------------------------------------------------
        # 1) XY trajectory with goal marked
        # -------------------------------------------------
        plt.figure()
        plt.plot(x[sl], y[sl], label="trajectory")
        if len(x) > 0 and np.isfinite(x[0]) and np.isfinite(y[0]):
            plt.scatter([x[0]], [y[0]], label="start")
        if len(x) > 0 and np.isfinite(x[-1]) and np.isfinite(y[-1]):
            plt.scatter([x[-1]], [y[-1]], label="end")
        if np.isfinite(x_des) and np.isfinite(y_des):
            plt.scatter([x_des], [y_des], label="goal")
            plt.text(x_des, y_des, f"({x_des:.2f}, {y_des:.2f})", ha="left", va="bottom")
        plt.xlabel("x (m)")
        plt.ylabel("y (m)")
        plt.title(f"XY trajectory\n{Path(csv_path).name}")
        plt.legend()
        plt.grid(True)
        plt.axis("equal")
        savefig("traj_xy")

        # -------------------------------------------------
        # 2) Z tracking: z vs z_des
        # -------------------------------------------------
        plt.figure()
        plt.plot(t[sl], z[sl], label="z")
        if np.isfinite(z_des):
            plt.axhline(z_des, linestyle="--", label=f"z_des = {z_des:.2f}")
        plt.xlabel("t (s)")
        plt.ylabel("z (m)")
        plt.title(f"Z tracking\n{Path(csv_path).name}")
        plt.legend()
        plt.grid(True)
        savefig("z_tracking")

        # -------------------------------------------------
        # 3) Yaw tracking: yaw vs yaw_des
        # -------------------------------------------------
        plt.figure()
        plt.plot(t[sl], yaw[sl], label="yaw_deg")

        if np.isfinite(yaw_des).any():
            yaw_des_plot = yaw_des.copy()

            # Visualization fix only: show +180 instead of -180
            yaw_des_plot[np.isclose(yaw_des_plot, -180.0, atol=1e-6)] = 180.0

            plt.plot(t[sl], yaw_des_plot[sl], "--", label="yaw_des_deg")

            yaw_des_val = yaw_des_plot[np.isfinite(yaw_des_plot)][0]
            plt.text(t[-1], yaw_des_val, f"{yaw_des_val:.1f}°", ha="right", va="bottom")

        plt.xlabel("t (s)")
        plt.ylabel("Yaw (deg)")
        plt.title(f"Yaw tracking\n{Path(csv_path).name}")
        plt.legend()
        plt.grid(True)
        savefig("yaw_tracking")

        # -------------------------------------------------
        # 4) Yaw error vs time
        # -------------------------------------------------
        plt.figure()
        plt.plot(t[sl], yaw_err[sl], label="yaw_err_deg")
        plt.axhline(0.0, linestyle="--")
        plt.xlabel("t (s)")
        plt.ylabel("Yaw error (deg)")
        plt.title(f"Yaw error vs time\n{Path(csv_path).name}")
        plt.legend()
        plt.grid(True)
        savefig("yaw_error")

        # -------------------------------------------------
        # 5) XY distance to goal: e_xy_norm vs time
        # -------------------------------------------------
        plt.figure()
        plt.plot(t[sl], e_xy_norm[sl], label="e_xy_norm")
        plt.xlabel("t (s)")
        plt.ylabel("Distance to goal in XY (m)")
        plt.title(f"XY distance-to-go\n{Path(csv_path).name}")
        plt.legend()
        plt.grid(True)
        savefig("xy_distance_to_goal")

    if args.show or not save:
        plt.show()


if __name__ == "__main__":
    main()